name = "BasicNBodySim"
uuid = "6c488c53-4985-4abe-b56f-7920498f068c"
authors = ["Aiden Rohrbach <arohrbachj@protonmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
